### ISSUE TITLE
`MultiDict.copy()` doesn't work with `istr` keys

### ISSUE THREAD

**Issue by alexsdutton** [aio-libs/multidict#11]
Here's a small test case:

    >>> import multidict
    >>> m=multidict.CIMultiDict({multidict.istr('Foo'): 'bar'})
    >>> m.copy()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "multidict/_multidict.pyx", line 325, in multidict._multidict.MultiDict.copy (multidict/_multidict.c:6830)
      File "multidict/_multidict.pyx", line 251, in multidict._multidict.MultiDict.__init__ (multidict/_multidict.c:5495)
      File "multidict/_multidict.pyx", line 289, in multidict._multidict.MultiDict._extend (multidict/_multidict.c:6115)
    TypeError: Expected str, got istr

`MultiDict._extend` expects every key to be a str. `aiohttp.hdrs`creates `istr` objects, so `request.headers.copy()` doesn't work.

**Comment by asvetlov** [comment]
Good catch!
I'll fix it in a few hours.

**Comment by asvetlov** [comment]
Fixed by 	c79c3a3 and released as `multidict==2.1.1"
