### ISSUE TITLE
ModuleNotFoundError: No module named 'multidict'

### ISSUE THREAD

**Issue by EpicHacker** [aio-libs/multidict#277]
I have this code for a discord bot, using discord.py and discord-rewrite. When running it, I get this error. ModuleNotFoundError: No module named 'multidict'. I have this installed, cause when i run `pip install multidict`, it says I have it and it also shows up on `pip list`
Here is the exact error:
`Traceback (most recent call last):
  File "C:/Users/TEST/Desktop/Coding Shared/Discord Bots/Loaf bot/Bot.py.a2r.py", line 1, in <module>
    import discord
  File "C:\Python36\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "C:\Python36\lib\site-packages\discord\client.py", line 30, in <module>
    from .guild import Guild
  File "C:\Python36\lib\site-packages\discord\guild.py", line 39, in <module>
    from .channel import *
  File "C:\Python36\lib\site-packages\discord\channel.py", line 31, in <module>
    from .webhook import Webhook
  File "C:\Python36\lib\site-packages\discord\webhook.py", line 27, in <module>
    import aiohttp
  File "C:\Python36\lib\site-packages\aiohttp\__init__.py", line 5, in <module>
    from . import hdrs  # noqa
  File "C:\Python36\lib\site-packages\aiohttp\hdrs.py", line 6, in <module>
    from multidict import istr
ModuleNotFoundError: No module named 'multidict'`

This should just work, since multidict _is_ installed on my system. Git is also installed.
How do i get this to work?

**Comment by webknjaz** [comment]
You probably installed it in different env. Learn how virtualenv works and figure out which python runs your app and which python has access to multidict and make them the same.

**Comment by EpicHacker** [comment]
i just realized
its installed in a different place

**Comment by EpicHacker** [comment]
Fixed it!
Reinstalled it on the system.
