### ISSUE TITLE
latest multidict does not have an 32 and 64 bit wheel for Python 3.6 for windows and linux.

### ISSUE THREAD

**Issue by AraHaan** [aio-libs/multidict#59]
Because the latest release does not have an python 3.6 wheel multidict, now breaks installing all of my discord bot's dependencies. The bad part about that is the bot is not supposed to be offline very ling but yet multidict and the latest yarl breaks it for python 3.6 Please fix these issues.

For more information see https://github.com/aio-libs/aiohttp/issues/1727

The entire output of the console (including the failure) is this:

```
Collecting discord.py (from -r requirements.txt (line 1))
  Using cached discord.py-0.16.7.tar.gz
Collecting aiohttp (from -r requirements.txt (line 2))
  Using cached aiohttp-1.3.5.tar.gz
Collecting PyNacl (from -r requirements.txt (line 3))
  Using cached PyNaCl-1.1.1-cp36-cp36m-win32.whl
Collecting pycares (from -r requirements.txt (line 4))
  Using cached pycares-2.1.1.tar.gz
Collecting cchardet (from -r requirements.txt (line 5))
  Using cached cchardet-1.1.3-cp36-cp36m-win32.whl
Collecting cffi (from -r requirements.txt (line 6))
  Using cached cffi-1.9.1-cp36-cp36m-win32.whl
Collecting multidict (from -r requirements.txt (line 7))
  Using cached multidict-2.1.4.tar.gz
Collecting yarl (from -r requirements.txt (line 8))
  Using cached yarl-0.10.0.tar.gz
Collecting discord.webhooks (from -r requirements.txt (line 9))
  Using cached discord.webhooks-0.0.2.tar.gz
Collecting websockets<4.0,>=3.1 (from discord.py->-r requirements.txt (line 1))
  Using cached websockets-3.2-py33.py34.py35-none-any.whl
Collecting chardet (from aiohttp->-r requirements.txt (line 2))
  Using cached chardet-2.3.0-py2.py3-none-any.whl
Collecting async_timeout>=1.1.0 (from aiohttp->-r requirements.txt (line 2))
  Using cached async_timeout-1.2.0-py3-none-any.whl
Collecting six (from PyNacl->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pycparser (from cffi->-r requirements.txt (line 6))
  Using cached pycparser-2.17.tar.gz
Installing collected packages: chardet, multidict, async-timeout, yarl, aiohttp,
 websockets, discord.py, pycparser, cffi, six, PyNacl, pycares, cchardet, discor
d.webhooks
  Running setup.py install for multidict ... error
    Complete output from command E:\Python360\python.exe -u -c "import setuptool
s, tokenize;__file__='E:\\Users\\Elsword\\AppData\\Local\\Temp\\pip-build-j53pka
8u\\multidict\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read
().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" instal
l --record E:\Users\Elsword\AppData\Local\Temp\pip-61352pwp-record\install-recor
d.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\multidict
    copying multidict\_multidict_py.py -> build\lib.win32-3.6\multidict
    copying multidict\__init__.py -> build\lib.win32-3.6\multidict
    running egg_info
    writing multidict.egg-info\PKG-INFO
    writing dependency_links to multidict.egg-info\dependency_links.txt
    writing top-level names to multidict.egg-info\top_level.txt
    reading manifest file 'multidict.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    warning: no previously-included files found matching 'multidict\_multidict.h
tml'
    warning: no previously-included files found matching 'multidict\_multidict.*
.so'
    warning: no previously-included files found matching 'multidict\_multidict.p
yd'
    warning: no previously-included files found matching 'multidict\_multidict.*
.pyd'
    no previously-included directories found matching 'docs\_build'
    writing manifest file 'multidict.egg-info\SOURCES.txt'
    copying multidict\__init__.pyi -> build\lib.win32-3.6\multidict
    copying multidict\_multidict.c -> build\lib.win32-3.6\multidict
    copying multidict\_multidict.pyx -> build\lib.win32-3.6\multidict
    running build_ext
    building 'multidict._multidict' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\multidict
    E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo
 /Ox /W3 /GL /DNDEBUG /MD -IE:\Python360\include -IE:\Python360\include "-IE:\Pr
ogram Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IE:\Program Files (
x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IE:\Program Files (x86)\W
indows Kits\10\include\10.0.10586.0\ucrt" "-IE:\Program Files (x86)\Windows Kits
\NETFXSDK\4.6.1\include\um" "-IE:\Program Files (x86)\Windows Kits\10\include\10
.0.10586.0\shared" "-IE:\Program Files (x86)\Windows Kits\10\include\10.0.10586.
0\um" "-IE:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt" "-IE
:\Program Files (x86)\Microsoft Visual Studio\VC98\atl\include" "-IE:\Program Fi
les (x86)\Microsoft Visual Studio\VC98\mfc\include" "-IE:\Program Files (x86)\Mi
crosoft Visual Studio\VC98\include" /Tcmultidict/_multidict.c /Fobuild\temp.win3
2-3.6\Release\multidict/_multidict.obj
    _multidict.c
    multidict/_multidict.c(11): fatal error C1083: Cannot open include file: 'Py
thon.h': No such file or directory
    ************************************************************
    Cannot compile C accelerator module, use pure python version
    ************************************************************
    running install
    running build
    running build_py
    creating build\lib
    creating build\lib\multidict
    copying multidict\_multidict_py.py -> build\lib\multidict
    copying multidict\__init__.py -> build\lib\multidict
    running egg_info
    writing multidict.egg-info\PKG-INFO
    writing dependency_links to multidict.egg-info\dependency_links.txt
    writing top-level names to multidict.egg-info\top_level.txt
    reading manifest file 'multidict.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in dis
tribution
    warning: no previously-included files found matching 'multidict\_multidict.h
tml'
    warning: no previously-included files found matching 'multidict\_multidict.*
.so'
    warning: no previously-included files found matching 'multidict\_multidict.p
yd'
    warning: no previously-included files found matching 'multidict\_multidict.*
.pyd'
    no previously-included directories found matching 'docs\_build'
    writing manifest file 'multidict.egg-info\SOURCES.txt'
    copying multidict\__init__.pyi -> build\lib\multidict
    copying multidict\_multidict.c -> build\lib\multidict
    copying multidict\_multidict.pyx -> build\lib\multidict
    running install_lib
    running install_egg_info
    removing 'E:\Python360\Lib\site-packages\multidict-2.1.4-py3.6.egg-info' (an
d everything under it)
    Copying multidict.egg-info to E:\Python360\Lib\site-packages\multidict-2.1.4
-py3.6.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "E:\Python360\lib\distutils\_msvccompiler.py", line 382, in compile
        self.spawn(args)
      File "E:\Python360\lib\distutils\_msvccompiler.py", line 501, in spawn
        return super().spawn(cmd)
      File "E:\Python360\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "E:\Python360\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "E:\Python360\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'E:\\Program Files (x86)\\Micro
soft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Users\Elsword\AppData\Local\Temp\pip-build-j53pka8u\multidict\set
up.py", line 46, in build_extension
        build_ext.build_extension(self, ext)
      File "E:\Python360\lib\distutils\command\build_ext.py", line 533, in build
_extension
        depends=ext.depends)
      File "E:\Python360\lib\distutils\_msvccompiler.py", line 384, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'E:\\Program Files (x86)\\Microsoft V
isual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Users\Elsword\AppData\Local\Temp\pip-build-j53pka8u\multidict\set
up.py", line 103, in <module>
        setup(**args)
      File "E:\Python360\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "E:\Python360\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "E:\Python360\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Python360\lib\site-packages\setuptools\command\install.py", line
61, in run
        return orig.install.run(self)
      File "E:\Python360\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "E:\Python360\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "E:\Python360\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Python360\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "E:\Python360\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "E:\Python360\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Users\Elsword\AppData\Local\Temp\pip-build-j53pka8u\multidict\set
up.py", line 40, in run
        build_ext.run(self)
      File "E:\Python360\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "E:\Python360\lib\distutils\command\build_ext.py", line 448, in build
_extensions
        self._build_extensions_serial()
      File "E:\Python360\lib\distutils\command\build_ext.py", line 473, in _buil
d_extensions_serial
        self.build_extension(ext)
      File "E:\Users\Elsword\AppData\Local\Temp\pip-build-j53pka8u\multidict\set
up.py", line 49, in build_extension
        raise BuildFailed()
    __main__.BuildFailed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "E:\Users\Elsword\AppData\Local\Temp\pip-build-j53pka8u\multidict\set
up.py", line 110, in <module>
        setup(**args)
      File "E:\Python360\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "E:\Python360\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "E:\Python360\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Python360\lib\site-packages\setuptools\command\install.py", line
61, in run
        return orig.install.run(self)
      File "E:\Python360\lib\distutils\command\install.py", line 557, in run
        self.run_command(cmd_name)
      File "E:\Python360\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "E:\Python360\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "E:\Python360\lib\site-packages\setuptools\command\install_scripts.py
", line 35, in run
        bw_cmd = self.get_finalized_command("bdist_wininst")
      File "E:\Python360\lib\distutils\cmd.py", line 298, in get_finalized_comma
nd
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "E:\Python360\lib\distutils\dist.py", line 846, in get_command_obj
        klass = self.get_command_class(command)
      File "E:\Python360\lib\site-packages\setuptools\dist.py", line 489, in get
_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "E:\Python360\lib\site-packages\pkg_resources\__init__.py", line 2291
, in load
        return self.resolve()
      File "E:\Python360\lib\site-packages\pkg_resources\__init__.py", line 2297
, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "E:\Python360\lib\site-packages\setuptools\command\bdist_wininst.py",
 line 1, in <module>
        import distutils.command.bdist_wininst as orig
    ModuleNotFoundError: No module named 'distutils.command.bdist_wininst'

    ----------------------------------------
Command "E:\Python360\python.exe -u -c "import setuptools, tokenize;__file__='E:
\\Users\\Elsword\\AppData\\Local\\Temp\\pip-build-j53pka8u\\multidict\\setup.py'
;f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n')
;f.close();exec(compile(code, __file__, 'exec'))" install --record E:\Users\Elsw
ord\AppData\Local\Temp\pip-61352pwp-record\install-record.txt --single-version-e
xternally-managed --compile" failed with error code 1 in E:\Users\Elsword\AppDat
a\Local\Temp\pip-build-j53pka8u\multidict\
Press any key to continue . . .
```

btw how did you guys get the rst to show batdges properly and stuff? I could never get the rst to show properly in pypi:

https://pypi.python.org/pypi/discord.webhooks<-- one of my packages I could never get the rst to act right on.

**Comment by AraHaan** [comment]
Alright so both of these PR's would have to be merged so it can close this issue:
https://github.com/aio-libs/multidict/pull/60
https://github.com/aio-libs/yarl/pull/68

**Comment by fafhrd91** [comment]
merged
